//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketWebappAireLogic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ticketTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ticketTable()
        {
            this.commentTables = new HashSet<commentTable>();
        }
    
        public int ticketID { get; set; }
        public string ticketTitle { get; set; }
        public string ticketDescription { get; set; }
        public string ticketStatus { get; set; }
        public Nullable<int> userID { get; set; }
        public string ticketCreationTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [System.Runtime.Serialization.IgnoreDataMember]
        public  ICollection<commentTable> commentTables { get; set; }
        public  userTable userTable { get; set; }
    }
}
