//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketWebappAireLogic.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ticketDBEntities2 : DbContext
    {
        public ticketDBEntities2()
            : base("name=ticketDBEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<commentTable> commentTables { get; set; }
        public virtual DbSet<ticketTable> ticketTables { get; set; }
        public virtual DbSet<userTable> userTables { get; set; }
    }
}
